--drop table if exists 'STUDENT';
CREATE TABLE IFNOT EXISTS 'STUDENT' (
  'ID' INT(10) UNSIGNED NOT NULL,
  'NAME' VARCHAR(100) NOT NULL,
  'AGE' INT(3),
  'JOINING_DATE' DATE,
  PRIMARY KEY ('ID')
) --ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;